/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  public void test(){

    HashTable<String, Integer> grades = new HashTable<String, Integer>();

    assertTrue(grades.isEmpty());

    grades.add("Sara",100);
    assertEquals(1,grades.getSize());

    grades.add("LEEN", 30);
    assertEquals(2,grades.getSize());
    assertFalse(grades.isEmpty());

    grades.remove("LEEN");
    assertEquals(1,grades.getSize());

    assertTrue(grades.contains("SARA"));
    assertFalse(grades.contains("GHADEER"));

    grades.remove("SARA");
    assertTrue(grades.isEmpty());


  }
}
