/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
  public static void main(String[] args) {


    Graph graph = new Graph();

    graph.addVertex("Sara");
    graph.addVertex("Leen");
    graph.addVertex("Maria");
    graph.addVertex("Alaa");

    graph.addEdge("Sara","Leen");
    graph.addEdge("Sara", "Maria");
    graph.addEdge("Sara", "Alaa");
    graph.addEdge("Leen","Maria");
    graph.addEdge("Maria","Alaa");
    graph.addEdge("Alaa", "Leen");

    System.out.println(graph.printGraph());

    graph.removeEdge("Alaa", "Maria");
    System.out.println();
    System.out.println("delete edge --> "+graph.printGraph());

    graph.removeVertex("Motasim");
    System.out.println();
    System.out.println("delete vertex --> " + graph.printGraph());

    System.out.println();
    System.out.println(graph.getVertices());

    System.out.println();
    System.out.println(graph.getNeighbors("Leen"));

    System.out.println();
    System.out.println(graph.breadthTraverse(graph, "Alaa"));

    System.out.println();
    System.out.println(graph.depthFirstTraverse(graph, "Alaa"));

    System.out.println();
    System.out.println(graph.size());

  }
}
