/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {



      BinarySearchTree<Integer> newTree = new BinarySearchTree<>();

      newTree.add(50);
      newTree.add(40);
      newTree.add(60);
      newTree.add(70);
      newTree.add(20);

      System.out.println(newTree.contain(80));
      System.out.println(newTree.contain(70));

      System.out.println(new App().getGreeting());

    }
}
