/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import BinaryTree.BinaryTree;
import BinaryTree.Node;

public class App {
  public static void main(String[] args) {

    HashTable<String, Integer> grades = new HashTable<String, Integer>();

    grades.add("Sara",100);
    grades.add("LEEN", 30);
    grades.add("GHADEER", 10);
    grades.add("Jason", 5);

    System.out.println("The size is => " + grades.getSize());
    System.out.println(grades.get("Sara"));
    System.out.println("Delete LEEN => " + grades.remove("LEEN"));
    System.out.println("The size is => " + grades.getSize());
    System.out.println(grades.contains("ss"));
    System.out.println(grades.contains("Sara"));


    String paragraph1 = "Once upon a time, there was a brave princess who...";
    String paragraph2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only";
    String paragraph3= "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York";
    System.out.println(grades.repeatedWord(paragraph3));



    //////////////////////////////////////////////////32//////////////////////

    HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
    BinaryTree tree1 = new BinaryTree();
    BinaryTree tree2 = new BinaryTree();
    tree1.setRoot(new Node(150));
    tree1.getRoot().setLeft(new Node(100));
    tree1.getRoot().setRight(new Node(250));
    tree1.getRoot().getRight().setLeft(new Node(200));
    tree1.getRoot().getRight().setRight(new Node(350));
    tree1.getRoot().getRight().getRight().setLeft(new Node(300));
    tree1.getRoot().getRight().getRight().setRight(new Node(500));
    tree1.getRoot().getLeft().setLeft(new Node(75));
    tree1.getRoot().getLeft().setRight(new Node(160));
    tree1.getRoot().getLeft().getRight().setLeft(new Node(125));
    tree1.getRoot().getLeft().getRight().setRight(new Node(175));
    tree2.setRoot(new Node(42));
    tree2.getRoot().setLeft(new Node(100));
    tree2.getRoot().setRight(new Node(600));
    tree2.getRoot().getRight().setLeft(new Node(200));
    tree2.getRoot().getRight().setRight(new Node(350));
    tree2.getRoot().getRight().getRight().setLeft(new Node(4));
    tree2.getRoot().getRight().getRight().setRight(new Node(500));
    tree2.getRoot().getLeft().setLeft(new Node(15));
    tree2.getRoot().getLeft().setRight(new Node(160));
    tree2.getRoot().getLeft().getRight().setLeft(new Node(125));
    tree2.getRoot().getLeft().getRight().setRight(new Node(175));
    System.out.println(trees.treeIntersection(tree1,tree2));








  }


  ////////////////////////////////////////32////////////////////////////////////


}
