/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {
  public static void main(String[] args) {

    HashTable<String, Integer> grades = new HashTable<String, Integer>();

    grades.add("Hatem",100);
    grades.add("Tareq", 30);
    grades.add("Doaa", 10);
    grades.add("Jason", 5);

    System.out.println("The size is => " + grades.getSize());
    System.out.println(grades.get("Hatem"));
    System.out.println("Delete Tareq => " + grades.remove("Tareq"));
    System.out.println("The size is => " + grades.getSize());
    System.out.println(grades.contains("ss"));
    System.out.println(grades.contains("Hatem"));
  }
}
