/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package k.ary.tree;

import java.util.LinkedList;
import java.util.Queue;

public class App {



  public static KAryTree<String> fizzBuzzTree(KAryTree<Integer> kTree){
    KAryTree<String> outTree = new KAryTree<>(kTree.K);

    Queue<Node> queue = new LinkedList<>();
    if(kTree.isNotEmpty()){
      queue.add(kTree.root);
      while(!queue.isEmpty()){

        Node<Integer> currentNode = queue.poll();

        String currentValue;
        if(currentNode.value % 3 == 0 && currentNode.value % 5 ==0 )
          currentValue = "FizzBuzz";
        else if((int)currentNode.value % 3 == 0)
          currentValue="Fizz";
        else if((int)currentNode.value % 5 == 0)
          currentValue="Buzz";
        else
          currentValue=currentNode.value.toString();

        outTree.add(currentValue);

        if(! currentNode.children.isEmpty())
          queue.addAll(currentNode.children);
      }
    }
    return outTree;
  }
  public static void main(String[] args) {
    KAryTree<Integer> tree = new  KAryTree<>(3);
    Node<Integer> node = new Node<>(15);
    tree.root = node;
    tree.add(1);
    tree.add(2);
    tree.add(3);
    tree.add(4);
    System.out.println(tree);
    System.out.println(fizzBuzzTree(tree));

  }
}
