/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {

    LinkedList linkedList = new LinkedList();
    linkedList.insert("a");
    linkedList.insert("b");
    linkedList.insert("c");
    linkedList.insert("d");
    linkedList.insert("e");


    System.out.println(linkedList.include("c"));
    System.out.println(linkedList.include("x"));

    System.out.println(linkedList);

  }


}
